kyoheiu/felix

src/run.rs, src/state.rs
Closes https://github.com/kyoheiu/felix/issues/31
=> Add show/hide hidden files or dirs option

Cargo.toml, config.toml, src/config.rs, src/state.rs
=> Revert "Improvements to Linux support"

Cargo.lock, Cargo.toml, src/config.rs, src/errors.rs, src/functions.rs, src/run.rs, src/session.rs, src/state.rs
This PR enables to toggle whether to show preview (contents if text file, tree if directory) on the right half of terminal.
=> [Experimental] Implement preview

CHANGELOG.md, config.toml, src/config.rs, src/functions.rs, src/run.rs, src/state.rs
This PR will enable you to set your own default commang at the first launch.
Also includes some refactoring.
=> Better config

README.md, src/run.rs, src/state.rs
Fixed some typos
Added the windows description to the README.md since it was missing
=> Fix typo and add windows config description

CHANGELOG.md, Cargo.lock, Cargo.toml, config.toml, src/config.rs, src/errors.rs, src/layout.rs, src/main.rs, src/run.rs, src/session.rs, src/state.rs
=> Add horizontal split

config.toml, config.yaml, src/config.rs, src/errors.rs, src/functions.rs, src/layout.rs, src/nums.rs, src/run.rs, src/session.rs, src/state.rs, src/term.rs
#135 
Implement `/`, `n`, `N`  of Vim (Replacing the filter mode)
=> New featrue: Search by keyword

Cargo.lock, Cargo.toml, config.yaml, src/config.rs, src/errors.rs, src/session.rs, src/state.rs
=> Migrate to yaml from toml

.gitignore, Cargo.lock, Cargo.toml, src/errors.rs, src/functions.rs, src/magicbytes.rs, src/main.rs, src/run.rs
=> Add: feature to extract archive file

Cargo.lock, Cargo.toml, src/errors.rs, src/state.rs
=> Fix: Use double-fork on linux

src/functions.rs, src/run.rs
=> Add create_dir_all for config_dir/data_local_dir

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/help.rs, src/run.rs
=> Fix: Disable modifiers unless explicitly implemented

Cargo.lock, Cargo.toml, src/functions.rs, src/layout.rs, src/state.rs
Also fix the preview space height.
=> Properly handle wide chars

src/run.rs
=> Fix: If you scroll the previewed text, the redrawing is disabled

src/help.rs
so that we don't have to update the version in `help.rs` manually with each release :bear:
=> Use dynamic version in help text

README.md, src/help.rs
=> Add example for Rgb and AnsiValue

src/run.rs
=> Explicitly save the position before entering the alternate screen

src/run.rs
=> Allow multiple arguments for zoxide query

src/config.rs, src/run.rs, src/state.rs
=> Add ignore_case option

src/state.rs
=> Show items linked to directory in the directory section

src/run.rs
=> Fix: Receive multiple arguments

CHANGELOG.md, Cargo.lock, Cargo.toml, src/run.rs, src/state.rs
=> Show target path of symlink items at the footer

src/layout.rs, src/state.rs
=> Add PreviewType::TooBigImage to handle large text file in preview area

src/layout.rs, src/state.rs
=> Add PreviewType::TooBigText to handle large text file in preview area
